nama =input("Nama                 : ")
nim  =input("NIM                  : ")
kelas=input("Kelas Paralel        : ")
ttl  =input("Tempat/Tanggal Lahir : ")
almt =input("Alamat               : ")
hobby=input("Hobby                : ")
hp   =input("No.HP                : ")
print("\nNama                 : ",nama)
print("NIM                  : ",nim)
print("Kelas Paralel        : ",kelas)
print("Tempat/Tanggal Lahir : ",ttl)
print("Alamat               : ",almt)
print("Hobby                : ",hobby)
print("No.HP                : ",hp)